app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/root
      username: root
      password: password
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

